---

- name: 3.6 Disable IP v6
  copy:
      dest: "/etc/sysctl.d/98-disable_ipv6.conf"
      content: 
        net.ipv6.conf.all.disable_ipv6 = 1
        net.ipv6.conf.default.disable_ipv6 = 1
  tags:
    - level-2
    - "3.6"
    - scored
