# Standards: 0.11

---

# 3.5.1.4 Ensure firewall rules exist for all open ports
- name: 3.5.1.4 - Ensure firewall rules exist for all open ports
  debug:
    msg: "WARNING - We are already checking this as part of security groups."
  tags:
    - level-1
    - section-3
    - "3.5.1.4"
    - not-scored

#do this using cloud-init scripts instead
- name: 3.5.1.4 - Ensure firewall rules exist for accepting SSH connections
  lineinfile:
      path: /var/lib/cloud/scripts/per-once/00-firewall.sh
      line: iptables -A INPUT -p tcp --dport 22 -j ACCEPT
      insertafter: EOF
  tags:
    - level-1
    - section-3
    - "3.5.1.4"
    - not-scored

#setup IPTABLES as a service
- name: 3.5.1.4 - install IPTABLES Service
  yum: 
        name: iptables-service
        state: latest
  tags:
    - level-1
    - section-3
    - "3.5.1.4"
    - not-scored

#Set iptables as enabled service
- name: 3.5.1.4 - enable iptables service
  systemd:
        enabled: yes
        name: iptables
  tags:
    - level-1
    - section-3
    - "3.5.1.4"
    - not-scored

#Save iptables for next boot
- name: 3.5.1.4 - save iptables for next boot
  lineinfile:
      path: /var/lib/cloud/scripts/per-once/00-firewall.sh
      line: service iptables save
      insertafter: EOF
  tags:
    - level-1
    - section-3
    - "3.5.1.4"
    - not-scored
