# Standards: 0.11
---

# 4.2.4 Ensure permissions on all logfiles are configured

- name: 4.2.4 - Ensure permissions on all logfiles are configured
  shell: "find -L /var/log -type f -exec chmod g-wx,o-rwx {} +"
  tags:
    - level-1
    - section-4
    - "4.2.4"
    - scored

- name: 4.2.4 - Ensure permissions on all logfiles are configured
  lineinfile: 
      path: /etc/rsyslog.conf
      line: '$umask 000'
      insertbefore: BOF
  tags:
    - level-1
    - section-4
    - "4.2.4"
    - scored

- name: 4.2.4 - Ensure permissions on all logfiles are configured (wtmp)
  copy:
      remote_src: yes
      src: /usr/lib/tmpfiles.d/var.conf
      dest: /etc/tmpfiles.d
  tags:
    - level-1
    - section-4
    - "4.2.4"
    - scored

- name: 4.2.4 - Ensure permissions on all logfiles are configured (wtmp)
  lineinfile:
      path: /etc/tmpfiles.d/var.conf
      regexp: '^.*wtmp 0664.*'
      line: 'f /var/log/wtmp 0640 root utmp -'
  tags:
    - level-1
    - section-4
    - "4.2.4"
    - scored

- name: 4.2.4 - Ensure permissions on all logfiles are configured (dmesg)
  copy:
      remote_src: yes
      src: /usr/lib/systemd/system/rhel-dmesg.service
      dest: /etc/systemd/system
  tags:
    - level-1
    - section-4
    - "4.2.4"
    - scored

- name: 4.2.4 - Ensure permissions on all logfiles are configured (dmesg)
  lineinfile:
      path: /etc/systemd/system/rhel-dmesg.service
      regexp: ^ExecStart.*
      line: ExecStart=/etc/systemd/rhel-dmesg
  tags:
    - level-1
    - section-4
    - "4.2.4"
    - scored

- name: 4.2.4 - Ensure permissions on all logfiles are configured (dmesg)
  copy:
      remote_src: yes
      src: /usr/lib/systemd/rhel-dmesg
      dest: /etc/systemd
  tags:
    - level-1
    - section-4
    - "4.2.4"
    - scored

- name: 4.2.4 - Ensure permissions on all logfiles are configured (dmesg)
  lineinfile:
      path: /etc/systemd/rhel-dmesg
      insertafter: ^#!/bin/bash
      line: umask 0077  # added for hardening
  tags:
    - level-1
    - section-4
    - "4.2.4"
    - scored

- name: 4.2.4 - Ensure permissions on all logfiles are configured (cloud-init)
  copy:
      src: "{{ role_path }}/files/cloud-init-log-permissions.service"
      dest: /etc/systemd/system
  tags:
    - level-1
    - section-4
    - "4.2.4"
    - scored

- name: Enable service cloud-init-log-permissions.service and ensure it is not masked
  systemd:
      name: cloud-init-log-permissions
      enabled: yes
      masked: no
  tags:
    - level-1
    - section-4
    - "4.2.4"
    - scored
