# Standards: 0.11
---

# 5.3.3 Ensure password reuse is limited
- name: 5.3.3 - Ensure password reuse is limited (/etc/pam.d/system-auth)
  pamd:
    name: system-auth
    type: password
    control: sufficient
    module_path: pam_unix.so
    new_control: sufficient
    new_module_path: pam_unix.so
    new_type: password
    module_arguments: 'remember=5'
    state: args_present
  tags:
    - level-1
    - section-5
    - "5.3.3"
    - scored

- name: 5.3.3 - Ensure password reuse is limited (/etc/pam.d/password-auth)
  pamd:
    name: password-auth
    type: password
    control: sufficient
    module_path: pam_unix.so
    new_control: sufficient
    new_module_path: pam_unix.so
    new_type: password
    module_arguments: 'remember=5'
    state: args_present
  tags:
    - level-1
    - section-5
    - "5.3.3"
    - scored

- name: 5.3.3 - Ensure password reuse is limited (mv password-auth)
  command: mv /etc/pam.d/password-auth /etc/pam.d/password-auth-ansible
  tags:
    - level-1
    - section-5
    - "5.3.3"
    - scored

- name: 5.3.3 - Ensure password reuse is limited (symlink password-auth)
  file:
        src: /etc/pam.d/password-auth-ansible
        dest: /etc/pam.d/password-auth
        owner: root
        group: root
        state: link
  tags:
    - level-1
    - section-5
    - "5.3.3"
    - scored

- name: 5.3.3 - Ensure password reuse is limited (mv system-auth)
  command: cd /etc/pam.d && mv system-auth system-auth-ansible && ln -s /etc/pam.d/system-auth-ansible system-auth && cp system-auth system-auth.bak
  tags:
    - level-1
    - section-5
    - "5.3.3"
    - scored

